name: solar-system workflow

on:
 workflow_dispatch:
 push:
  branches:
  - main
  - 'feature/*'

env:
 MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
 MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
 MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}


jobs:
 unit-testing:
  name: unit testing
  strategy:
   matrix:
    nodejs_version: [18,24,20]
    os: [ubuntu-latest, macos-latest]
    exclude:
    - nodejs_version: 18
      os: macos-latest

  
  runs-on: ${{ matrix.os }}

  steps:
  -  name: checkout
     uses: actions/checkout@v7.0.1

  - name: setip node
    uses: actions/setup-node@v7
    with:
     node-version:  ${{ matrix.nodejs_version }}
    
  - name: install npm
    run: npm install

  - name: Unit testing
    id: nodejs-unit-testing-step
    run: npm test


  - name: archive test results
    if: failure() && steps.nodejs-unit-testing-step.outcome=='failure' || steps.nodejs-unit-testing-step.outcome=='success'
    uses: actions/upload-artifact@v7.0.1
    with:
     name: MOCHA-test-result
     path: test-results.xml
    

 code-coverage:
  name: code coverage
  needs: unit-testing
  runs-on: ubuntu-latest

  steps:
  - name: checkout
    uses: actions/checkout@v7.0.1

  - name: setip node
    uses: actions/setup-node@v7
    with:
     node-version:  ${{ matrix.nodejs_version }}
    
  - name: install npm
    run: npm install


  - name: run coverage
    continue-on-error: true
    run: npm run coverage


  - name: archive test results
    uses: actions/upload-artifact@v7.0.1
    with:
     name: code-coverage-report
     path: coverage
     retention-days: 5


  
    


  