name: solar-system workflow

on:
 workflow_dispatch:
 push:
  branches:
  - main
  - 'feature/*'

env:
 MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
 MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
 MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}


jobs:
 unit-testing:
  name: unit testing
  runs-on: ubuntu-latest
  steps:
  -  name: checkout
     uses: actions/checkout@v7.0.1

  - name: setip node
    uses: actions/setup-node@v7
    with:
     node-version: 24
    
  - name: install npm
    run: npm install

  - name: Unit testing
    continue-on-error: true
    run: npm test

  - name: archive test results
    uses: actions/upload-artifact@v7.0.1
    with:
     name: MOCHA-test-result
     path: test-results.xml
    
  

  